version: '3.8'
services:
  tracker:
    build:
      context: ./tracker
    restart: always
    ports:
      - "8082:8082"
    env_file:
      - db_config.env
    environment:
      - TRACKER_PASSWORD=${SECURE_PASSWORD}
    depends_on:
      - postgres
#      postgres:
#        condition: service_healthy
  postgres:
    image: postgres:14.5
    restart: always
#    ports:
#      - "25432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      #- pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${SECURE_PASSWORD}
      POSTGRES_USER: tracker
      POSTGRES_DB: tracker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  visualisation:
    image: visualisation
    restart: always
    ports:
      - "8084:8082"
    env_file:
      - db_config.env
    environment:
      - TRACKER_PASSWORD=${SECURE_PASSWORD}
    depends_on:
      - postgres
#      postgres:
#        condition: service_healthy

#volumes:
#  pgdata:
#    external: false